In [1]:
import pandas as pd
import numpy as np

In [2]:
nfl_data = pd.read_csv('NFL Play by Play 2009-2017 (v4).csv')
sf_permits = pd.read_csv('Building_Permits.csv')

C:\Users\Anjali Dontaraju\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\Anjali Dontaraju\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
nfl_data.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

##Function 1 : dictionary_apply_kwarg_funs that inputs **kwargs
The function outputs outputs from each i’th step of a data pipeline applied to a given dataset.

What this function should do : 
1.1 Making use of regular expressions findall command, find all steps defined by arguments of kwargs starting like “step_”. Name this variable how_many steps. This quantifies how many steps are in the data pipeline.

In [4]:
import re

In [140]:
nfl_sub = nfl_data.loc[:,'EPA':'Away_WP_pre'].head(10)

In [141]:
nfl_sub

        EPA    airEPA    yacEPA  Home_WP_pre  Away_WP_pre
0  2.014474       NaN       NaN     0.485675     0.514325
1  0.077907 -1.068169  1.146076     0.546433     0.453567
2 -1.402760       NaN       NaN     0.551088     0.448912
3 -1.712583  3.318841 -5.031425     0.510793     0.489207
4  2.097796       NaN       NaN     0.461217     0.538783
5 -0.696302       NaN       NaN     0.558929     0.441071
6 -0.179149 -0.343085  0.163935     0.578453     0.421547
7 -1.119477       NaN       NaN     0.582881     0.417119
8 -0.021313       NaN       NaN     0.617544     0.382456
9 -0.215293 -0.756894  0.541602     0.591489     0.408511

In [142]:
some_number1 = 2
some_number2 = 3
some_number3 = 4

In [143]:
axis = 1
output = {}
kwargs = {'input_':nfl_sub,'step_1':pd.DataFrame.dropna, 'arg_1':{'axis':axis,'thresh':some_number1},
          'step_2':pd.DataFrame.dropna, 'arg_2':{'axis':1,'thresh':some_number2},'step_3':pd.DataFrame.dropna, 'arg_3':{'axis':1,'thresh':some_number3}}

## Not needed 
def recognize_step_i(i,**kwargs):
    import re
    from operator import itemgetter
    fun_string = f"step_{i}"
    print(fun_string)
    arg_string = f"arg_{i}"
    print(arg_string)
    fun = re.findall('step_', ' ' .join(kwargs.keys()))
    #print(kwargs.keys())
    print(fun)

In [144]:
#if nfl_sub is not null:
#    output_ = dictionary_apply_kwarg_funs(**kwargs)

def dictionary_apply_kwarg_funs(**kwargs):
    import re
    from operator import itemgetter

    for j in range(1,4):
        how_many_steps = 1

        fun_string = f"step_{j}"
        #print(fun_string)
        arg_string = f"arg_{j}"
        #print(arg_string)
        fun = re.findall(fun_string, ' ' .join(kwargs.keys()))
        #print(fun.type())
        #print(kwargs.keys())
        how_many_steps = len(fun)
        print(fun)
        how_many_steps+=1
        output_ = {}
        #output_ = recognize_step_i()

        
    print(how_many_steps)


dictionary_apply_kwarg_funs(**kwargs)  ## Calling the function

['step_1']
['step_2']
['step_3']
2

In [124]:
intermediate = nfl_sub

## Have to continue 
if intermediate is not null:
    If it is not, then the function should enter a loop, looping over all the steps. 
    First define a unique identifier for the step as “step_{iteration_number+1}. 
    Call this variable step_ID.

In [174]:
def recognize_step_i(i, **kwargs):
    import re
    from operator import itemgetter
    #for i in range(1, len(how_many_steps)):
    for i in range(1,4):
        
        fun_string = f"step_{i}"
        #print(fun_string)
        arg_string = f"arg_{i}"
        key = re.findall(fun_string, ' ' .join(kwargs.keys()))
        key_arg = re.findall(arg_string, ' ' .join(kwargs.keys()))

        #print(*key)
        #print(*key_arg)
        #print(kwargs[key])  # Another method
        
        #key = re.findall(pattern,text) # test  step1 step2 step3
        fun1 = itemgetter(*key),(kwargs)
        #print(fun1)
        arg_dict = itemgetter(*key_arg),(kwargs)
        print(arg_dict)
        #res = list(map(itemgetter('*key'), kwargs)) 

        
recognize_step_i(3, **kwargs)

(operator.itemgetter('arg_1'), {'input_':         EPA    airEPA    yacEPA  Home_WP_pre  Away_WP_pre
0  2.014474       NaN       NaN     0.485675     0.514325
1  0.077907 -1.068169  1.146076     0.546433     0.453567
2 -1.402760       NaN       NaN     0.551088     0.448912
3 -1.712583  3.318841 -5.031425     0.510793     0.489207
4  2.097796       NaN       NaN     0.461217     0.538783
5 -0.696302       NaN       NaN     0.558929     0.441071
6 -0.179149 -0.343085  0.163935     0.578453     0.421547
7 -1.119477       NaN       NaN     0.582881     0.417119
8 -0.021313       NaN       NaN     0.617544     0.382456
9 -0.215293 -0.756894  0.541602     0.591489     0.408511, 'step_1': <function DataFrame.dropna at 0x00000175BB97AF28>, 'arg_1': {'axis': 1, 'thresh': 2}, 'step_2': <function DataFrame.dropna at 0x00000175BB97AF28>, 'arg_2': {'axis': 1, 'thresh': 3}, 'step_3': <function DataFrame.dropna at 0x00000175BB97AF28>, 'arg_3': {'axis': 1, 'thresh': 4}})
(operator.itemgetter('arg_2'), {'input_':         EPA    airEPA    yacEPA  Home_WP_pre  Away_WP_pre
0  2.014474       NaN       NaN     0.485675     0.514325
1  0.077907 -1.068169  1.146076     0.546433     0.453567
2 -1.402760       NaN       NaN     0.551088     0.448912
3 -1.712583  3.318841 -5.031425     0.510793     0.489207
4  2.097796       NaN       NaN     0.461217     0.538783
5 -0.696302       NaN       NaN     0.558929     0.441071
6 -0.179149 -0.343085  0.163935     0.578453     0.421547
7 -1.119477       NaN       NaN     0.582881     0.417119
8 -0.021313       NaN       NaN     0.617544     0.382456
9 -0.215293 -0.756894  0.541602     0.591489     0.408511, 'step_1': <function DataFrame.dropna at 0x00000175BB97AF28>, 'arg_1': {'axis': 1, 'thresh': 2}, 'step_2': <function DataFrame.dropna at 0x00000175BB97AF28>, 'arg_2': {'axis': 1, 'thresh': 3}, 'step_3': <function DataFrame.dropna at 0x00000175BB97AF28>, 'arg_3': {'axis': 1, 'thresh': 4}})
(operator.itemgetter('arg_3'), {'input_':         EPA    airEPA    yacEPA  Home_WP_pre  Away_WP_pre
0  2.014474       NaN       NaN     0.485675     0.514325
1  0.077907 -1.068169  1.146076     0.546433     0.453567
2 -1.402760       NaN       NaN     0.551088     0.448912
3 -1.712583  3.318841 -5.031425     0.510793     0.489207
4  2.097796       NaN       NaN     0.461217     0.538783
5 -0.696302       NaN       NaN     0.558929     0.441071
6 -0.179149 -0.343085  0.163935     0.578453     0.421547
7 -1.119477       NaN       NaN     0.582881     0.417119
8 -0.021313       NaN       NaN     0.617544     0.382456
9 -0.215293 -0.756894  0.541602     0.591489     0.408511, 'step_1': <function DataFrame.dropna at 0x00000175BB97AF28>, 'arg_1': {'axis': 1, 'thresh': 2}, 'step_2': <function DataFrame.dropna at 0x00000175BB97AF28>, 'arg_2': {'axis': 1, 'thresh': 3}, 'step_3': <function DataFrame.dropna at 0x00000175BB97AF28>, 'arg_3': {'axis': 1, 'thresh': 4}})

 1.2   Get the input dataset that is passed to the data pipeline (assume that it is passed to kwargs as “input_”). 
Also create a dictionary to store the output values from the data pipeline application, call the dictionary “output_

In [57]:
output_ = dictionary_apply_kwarg_funs(**kwargs)

dict_keys(['input_', 'step_1', 'arg_1', 'step_2', 'arg_2', 'step_3', 'arg_3'])

1.6.3 Get the function itself by applying itemgetter to the function over the kwargs.

## Not needed
import re
from operator import itemgetter
import pandas as pd

dic = {}
text = "I am test here"
#def process_something(text:str):
#   return text +"_something"

pattern = 'test'
dic[pattern] = pd.DataFrame.dropna # dic[test] = some function

key = re.findall(pattern,text) # test  step1 step2 step3
fun = itemgetter(*key)(dic)  #dic[test]
fun = dic[pattern]   # dic[test]
fun